name = "satler-bot"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-25"

[build]
command = "worker-build --release"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "satler-bot"
database_id = "cd056bc0-e55c-4b4c-98cd-4903f7c9959f"
